### ISSUE TITLE
Is it possible to configure the guzzle client ?

### ISSUE THREAD

**Issue by greg0ire** [Behat/WebApiExtension#18]
I'm testing an API that I just moved to `https`, and since I'm using a self-signed-certificate, guzzle gives me errors. Maybe the verify option should be set to false by default, and maybe it should even be configurable (not sure why though).

[Here](https://github.com/greg0ire/WebApiExtension/commit/0a9667c2419f86efbfa9676bd48b7f8776efa0a0) is how I worked around this problem.

**Comment by noetix** [comment]
Here is my work around (to set the `allow_redirects` setting):

```
<?php

namespace Escapee\CoreBundle\Behat;

use Behat\WebApiExtension\ServiceContainer\WebApiExtension as BaseWebApiExtension;
use Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition;

class WebApiExtension extends BaseWebApiExtension
{
    /**
     * {@inheritdoc}
     */
    public function configure(ArrayNodeDefinition $builder)
    {
        parent::configure($builder);

        $builder
            ->children()
                ->arrayNode('defaults')
                    ->children()
                        ->scalarNode('allow_redirects')
                            ->defaultTrue()
                        ->end()
                    ->end()
                ->end()
            ->end();
    }
}
```

`behat.yml`:
```
default:
    formatters:
        progress: ~
    extensions:
        Escapee\CoreBundle\Behat\WebApiExtension:
            defaults:
                allow_redirects: false
```
