### ISSUE TITLE
Installation guide is wrong

### ISSUE THREAD

**Issue by tom10271** [Behat/WebApiExtension#78]
https://github.com/Behat/WebApiExtension/blob/master/doc/index.rst

It should be:

```yaml
default:
    extensions:
        Behat\WebApiExtension\ServiceContainer\WebApiExtension: ~
```
